# send container 
apiVersion: batch/v1
kind: Job
metadata:
  name: send2myrabbit
spec:
  template:
    spec:
      containers:
      - name: sendjs2myrabbit
        image: sim007/sendjs2myrabbit
        env:
        - name:  HOSTNAME
          value: 10.1.1.4
# change IP                  
      restartPolicy: Never  